#!/usr/bin/python3
"""Generate the Gazebo test worlds (worlds/test/*.sdf) from scenarios.py.

    python3 scripts/make_test_worlds.py            # writes worlds/test/
Physics/sensor plugins match worlds/rock_terrain.sdf (DART, 1 ms, ogre2 sensors).
Every model carries a gz-sim-label-system label for the segmentation camera:
1 = ground/plateau, 2 = rock.
"""
import math
import os
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.realpath(__file__)))
from scenarios import SCENARIOS  # noqa: E402

HEADER = """<?xml version="1.0"?>
<!-- GENERATED by scripts/make_test_worlds.py - scenario '{name}': {desc} -->
<sdf version="1.9">
  <world name="vigil_rock_terrain">
    <gravity>0 0 -9.81</gravity>
    <physics name="physics" type="ignored"><max_step_size>0.001</max_step_size><real_time_factor>1</real_time_factor></physics>
    <plugin filename="gz-sim-physics-system" name="gz::sim::systems::Physics"><engine><filename>gz-physics-dartsim-plugin</filename></engine></plugin>
    <plugin filename="gz-sim-contact-system" name="gz::sim::systems::Contact"/>
    <plugin filename="gz-sim-user-commands-system" name="gz::sim::systems::UserCommands"/>
    <plugin filename="gz-sim-scene-broadcaster-system" name="gz::sim::systems::SceneBroadcaster"/>
    <plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors"><render_engine>ogre2</render_engine></plugin>
    <plugin filename="gz-sim-imu-system" name="gz::sim::systems::Imu"/>
    <scene><ambient>0.5 0.5 0.5 1</ambient><background>0.70 0.80 0.90 1</background><shadows>true</shadows><grid>false</grid></scene>
    <light name="sun" type="directional"><pose>0 0 20 0 0 0</pose><cast_shadows>true</cast_shadows>
      <diffuse>0.85 0.85 0.85 1</diffuse><specular>0.15 0.15 0.15 1</specular><direction>-0.4 0.2 -0.9</direction></light>
    <model name="ground_plane"><static>true</static>
      <link name="link">
        <collision name="collision"><geometry><plane><normal>0 0 1</normal><size>80 80</size></plane></geometry>
          <surface><friction><ode><mu>1.0</mu><mu2>1.0</mu2></ode></friction></surface></collision>
        <visual name="visual"><geometry><plane><normal>0 0 1</normal><size>80 80</size></plane></geometry>
          <material><ambient>0.42 0.36 0.30 1</ambient><diffuse>0.42 0.36 0.30 1</diffuse></material></visual>
      </link>
      <plugin filename="gz-sim-label-system" name="gz::sim::systems::Label"><label>1</label></plugin>
    </model>
"""

BOX = """    <model name="{name}"><static>true</static><pose>{x:.4f} {y:.4f} {z:.4f} 0 {pitch:.6f} 0</pose>
      <link name="link">
        <collision name="collision"><geometry><box><size>{sx:.4f} {sy:.4f} {sz:.4f}</size></box></geometry>
          <surface><friction><ode><mu>1.0</mu><mu2>1.0</mu2></ode></friction></surface></collision>
        <visual name="visual"><geometry><box><size>{sx:.4f} {sy:.4f} {sz:.4f}</size></box></geometry>
          <material><ambient>0.55 0.47 0.40 1</ambient><diffuse>0.55 0.47 0.40 1</diffuse></material></visual>
      </link>
      <plugin filename="gz-sim-label-system" name="gz::sim::systems::Label"><label>1</label></plugin>
    </model>
"""

SPHERE = """    <model name="{name}"><static>true</static><pose>{x:.4f} {y:.4f} {z:.4f} 0 0 0</pose>
      <link name="link">
        <collision name="collision"><geometry><sphere><radius>{r:.4f}</radius></sphere></geometry></collision>
        <visual name="visual"><geometry><sphere><radius>{r:.4f}</radius></sphere></geometry>
          <material><ambient>0.35 0.33 0.32 1</ambient><diffuse>0.35 0.33 0.32 1</diffuse></material></visual>
      </link>
      <plugin filename="gz-sim-label-system" name="gz::sim::systems::Label"><label>2</label></plugin>
    </model>
"""


def world_sdf(name, sc):
    out = [HEADER.format(name=name, desc=sc['desc'])]
    for k, o in enumerate(sc['objects']):
        if o['type'] == 'box':
            (x, y, z), (sx, sy, sz) = o['pos'], o['size']
            out.append(BOX.format(name=f'block_{k}', x=x, y=y, z=z, sx=sx, sy=sy, sz=sz, pitch=o.get('pitch', 0.0)))
        else:
            x, y, z = o['pos']
            out.append(SPHERE.format(name=f'rock_{k}', x=x, y=y, z=z, r=o['radius']))
    gx, gy = sc['goal']
    out.append(f"""    <!-- goal marker B (visual only) -->
    <model name="goal_B"><static>true</static><pose>{gx} {gy} {goal_height(sc) + 0.02:.3f} 0 0 0</pose>
      <link name="link"><visual name="v"><geometry><cylinder><radius>0.25</radius><length>0.02</length></cylinder></geometry>
        <material><ambient>1 0.2 0.8 1</ambient><diffuse>1 0.2 0.8 1</diffuse><emissive>0.6 0.1 0.5 1</emissive></material></visual></link>
    </model>
  </world>
</sdf>
""")
    return ''.join(out)


def goal_height(sc):
    """Top surface under B, so the marker sits on the terrain."""
    gx, gy = sc['goal']
    z = 0.0
    for o in sc['objects']:
        if o['type'] == 'box' and abs(o.get('pitch', 0.0)) < 1e-9:
            (x, y, cz), (sx, sy, sz) = o['pos'], o['size']
            if abs(gx - x) <= sx / 2 and abs(gy - y) <= sy / 2:
                z = max(z, cz + sz / 2)
    return z


def main(out_dir=None):
    out = Path(out_dir) if out_dir else Path(__file__).resolve().parents[1] / 'worlds/test'
    out.mkdir(parents=True, exist_ok=True)
    for name, sc in SCENARIOS.items():
        (out / f'{name}.sdf').write_text(world_sdf(name, sc))
        print('wrote', out / f'{name}.sdf')


if __name__ == '__main__':
    main(sys.argv[1] if len(sys.argv) > 1 else None)
