- direction: GZ_TO_ROS
  gz_topic_name: /clock
  gz_type_name: gz.msgs.Clock
  ros_topic_name: /clock
  ros_type_name: rosgraph_msgs/msg/Clock
- direction: GZ_TO_ROS
  gz_topic_name: /camera/image
  gz_type_name: gz.msgs.Image
  ros_topic_name: /camera/image
  ros_type_name: sensor_msgs/msg/Image
- direction: GZ_TO_ROS
  gz_topic_name: /camera/depth_image
  gz_type_name: gz.msgs.Image
  ros_topic_name: /camera/depth_image
  ros_type_name: sensor_msgs/msg/Image
- direction: GZ_TO_ROS
  gz_topic_name: /camera/camera_info
  gz_type_name: gz.msgs.CameraInfo
  ros_topic_name: /camera/camera_info
  ros_type_name: sensor_msgs/msg/CameraInfo
- direction: GZ_TO_ROS
  gz_topic_name: /thermal
  gz_type_name: gz.msgs.Image
  ros_topic_name: /thermal/image
  ros_type_name: sensor_msgs/msg/Image
- direction: GZ_TO_ROS
  gz_topic_name: /imu/data
  gz_type_name: gz.msgs.IMU
  ros_topic_name: /imu/data
  ros_type_name: sensor_msgs/msg/Imu
- direction: GZ_TO_ROS
  gz_topic_name: /sim/ground_truth
  gz_type_name: gz.msgs.Odometry
  ros_topic_name: /sim/ground_truth
  ros_type_name: nav_msgs/msg/Odometry
