rtabmap:
  ros__parameters:
    use_sim_time: true
    frame_id: base_footprint
    map_frame_id: map
    odom_frame_id: ''
    subscribe_depth: true
    subscribe_rgb: true
    subscribe_scan_cloud: true
    subscribe_odom_info: false
    approx_sync: true
    approx_sync_max_interval: 0.12
    topic_queue_size: 30
    sync_queue_size: 30
    qos_image: 2
    qos_camera_info: 2
    qos_scan: 2
    qos_imu: 2
    qos_odom: 1
    wait_for_transform: 0.3
    publish_tf: true
    Rtabmap/DetectionRate: '1'
    Reg/Strategy: '2'
    Reg/Force3DoF: 'false'
    RGBD/LinearUpdate: '0.15'
    RGBD/AngularUpdate: '0.08'
    RGBD/ProximityBySpace: 'true'
    RGBD/OptimizeFromGraphEnd: 'false'
    Vis/MinInliers: '12'
    Icp/VoxelSize: '0.1'
    Icp/PointToPlane: 'true'
    Icp/PointToPlaneK: '10'
    Icp/CorrespondenceRatio: '0.1'
    Optimizer/GravitySigma: '0.1'
    Grid/Sensor: '2'
    Grid/3D: 'true'
    Grid/CellSize: '0.15'
    Grid/FootprintLength: '2.0'
    Grid/FootprintWidth: '1.4'
    Grid/FootprintHeight: '1.2'
    GridGlobal/FootprintRadius: '0.65'
    Grid/RangeMax: '20'
    Grid/RayTracing: 'true'
    Grid/MaxGroundHeight: '0.15'
    Grid/MaxObstacleHeight: '2.5'
    Grid/NormalsSegmentation: 'false'
    GridGlobal/MinSize: '20'
    Mem/NotLinkedNodesKept: 'false'
    Mem/SaveDepth16Format: 'false'
    Mem/ImagePostDecimation: '1'
    Rtabmap/MemoryThr: '500'
    Mem/DepthCompressionFormat: .png
